sudo: false
cache: bundler
language: ruby
rvm:
  - 3.1
  - 3.0
  - 2.7
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
  - bundle exec rubocop
